### ISSUE TITLE
can not hook CreateFile func

### ISSUE THREAD

**Issue by guchangx** [m417z/global-inject-demo#3]
i use global inject demo want to hook some func, such as CreateFile
i exec cl.exe compile a test file test.cpp
cl.exe run must open test.cpp file by CreateFile.
form ProcessMonitor can indicate it.
<img width="1761" alt="image" src="https://github.com/m417z/global-inject-demo/assets/73569810/ef1138c5-6f21-4f40-bcb6-191f3e42741a">

but global inject demo can not hook this func,

<img width="1014" alt="image" src="https://github.com/m417z/global-inject-demo/assets/73569810/d9a305fe-1c56-4942-9d6b-4be63c07dd22">

![image](https://github.com/m417z/global-inject-demo/assets/73569810/a5d0d239-20b6-40ad-88aa-818fa86b9899)

i add a hook func like MessageBoxHook.
 you can see from my exec screenshot, i add CreateFile hook is success, because i create named pipline func,
but i can not hook CreateFile in read test.cpp file operator.

<img width="1679" alt="image" src="https://github.com/m417z/global-inject-demo/assets/73569810/f1a6e699-8809-4cc1-a567-079064ef90f0">

i make same test,but can not fix this issue. please help me.

**Comment by m417z** [comment]
On your screenshot, file access doesn't go through kernel32.CreateFileW, kernelbase.CreateFileW is called directly.

Try hooking kernelbase.CreateFileW directly, like this:
```cpp
HMODULE kernelBaseModule = GetModuleHandle(L"kernelbase.dll");
void* pCreateFileW = (void*)GetProcAddress(kernelBaseModule, "CreateFileW");
SetHook(pCreateFileW, (void*)CreateFileW_Hook, (void**)&CreateFileW_Original);
```

**Comment by guchangx** [comment]
Thank you very much. Let me have a try。

**Comment by guchangx** [comment]
thanks very much, that can work.
